name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: frontend
          sparse-checkout-cone-mode: true
      - uses: actions/setup-node@v5
        with:
          node-version: 24.9.0
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
        with:
          bun-version-file: "frontend/.bun-version"
      - name: Install dependencies
        run: bun install
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend
        env:
          VITE_BASE_PATH: ${{ github.event.repository.name }}
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: frontend/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
