name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: frontend
          sparse-checkout-cone-mode: true
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "frontend/.bun-version"
      - name: Install dependencies
        run: bun install
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
